var managers = [
	{owner: 'Sam Martinez', team: 'TB'},
	{owner: 'Evan Guckenberger', team: 'LA'},
	{owner: 'Winston Gaynor', team: 'ARI'},
	{owner: 'Derek Choops', team: ''},
	{owner: 'Luke Huffer', team: ''},
	{owner: 'Aidan Guckenberger', team: ''},
	{owner: 'KC Johnson', team: ''},
	{owner: 'Rory Deken', team: ''},
	{owner: 'Jake Bedinghaus', team: ''},
	{owner: 'Ricky Brayton', team: ''}
];

var teams = [
	{name: 'Arizona Cardinals', abrev: "ARI"},
	{name: 'Atlanta Falcons', abrev: "ATL"},
	{name: 'Baltimore Ravens', abrev: "BAL"},
	{name: 'Buffalo Bills', abrev: "BUF"},
	{name: 'Carolina Panthers', abrev: "CAR"},
	{name: 'Chicago Bears', abrev: "CHI"},
	{name: 'Cincinnati Bengals', abrev: "CIN"},
	{name: 'Cleveland Browns', abrev: "CLE"},
	{name: 'Dallas Cowboys', abrev: "DAL"},
	{name: 'Denver Broncos', abrev: "DEN"},
	{name: 'Detroit Lions', abrev: "DET"},
	{name: 'Green Bay Packers', abrev: "GB"},
	{name: 'Houston Texans', abrev: "HOU"},
	{name: 'Indianapolis Colts', abrev: "IND"},
	{name: 'Jacksonville Jaguars', abrev: "JAX"},
	{name: 'Kansas City Chiefs', abrev: "KC"},
	{name: 'Los Angeles Rams', abrev: "LA"},
	{name: 'Los Angeles Chargers', abrev: "LAC"},
	{name: 'Las Vegas Raiders', abrev: "LV"},
	{name: 'Miami Dolphins', abrev: "MIA"},
	{name: 'Minnesota Vikings', abrev: "MIN"},
	{name: 'New England Patriots', abrev: "NE"},
	{name: 'New Orleans Saints', abrev: "NO"},
	{name: 'New York Giants', abrev: "NYG"},
	{name: 'New York Jets', abrev: "NYJ"},
	{name: 'Philadelphia Eagles', abrev: "PHI"},
	{name: 'Pittsburgh Steelers', abrev: "PIT"},
	{name: 'Seattle Seahawks', abrev: "SEA"},
	{name: 'San Francisco 49ers', abrev: "SF"},
	{name: 'Tampa Bay Buccaneers', abrev: "TB"},
	{name: 'Tennessee Titans', abrev: "TEN"},
	{name: 'Washington Football Team', abrev: "WAS"}
];
